
spring:
  profiles:
    active: "dev"
  freemarker:
    enabled: false          
  zipkin:
    base-url: http://localhost:9411/  

server:
  port: ${customer.port} 
  
feign:
    hystrix:       
        enabled: true     
---

spring:
  profiles: dev
  jpa:
    database: MYSQL
    show-sql: true
  properties:
   hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/msa_cart
    username: root
    password: welcome_123!
    driver-class-name: com.mysql.cj.jdbc.Driver
     
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${customer.discovery.port}/eureka/ 
  instance:
    leaseRenewalIntervalInSeconds: 5  
    preferIpAddress: true
 
